import type { DatabaseViewsConfig, ViewConfig } from "../types/view.js";

export interface BasePropertySchema {
  readonly id: string;
  readonly type: string;
  readonly options?: Array<{ name: string; color?: string }>;
  readonly groups?: Array<{ name: string; color?: string; optionIds?: string[] }>;
}

export interface BaseFileOptions {
  readonly databaseId: string;
  readonly databaseName: string;
  readonly schema: Record<string, BasePropertySchema>;
  readonly viewsConfig: DatabaseViewsConfig;
  readonly folderPath: string;
}

type BasesViewType = "table" | "cards" | "list";

const NOTION_TO_BASES_VIEW: Record<string, BasesViewType | null> = {
  table: "table",
  gallery: "cards",
  list: "list",
  board: "cards",
  calendar: null,
  timeline: null,
  form: null,
  chart: null,
  map: null,
  dashboard: null,
};

export class BaseFileGenerator {
  generate(options: BaseFileOptions): string {
    const lines: string[] = [];

    lines.push(`# Auto-generated by Im-Nobsidian from Notion DB: ${options.databaseName}`);
    lines.push(`# Database ID: ${options.databaseId}`);
    lines.push("");

    this.writeFilters(lines, options.folderPath);
    this.writeFormulas(lines, options.viewsConfig.views);
    this.writePropertyDisplayNames(lines, options.schema);
    this.writeViews(lines, options.viewsConfig.views, options.schema);

    return lines.join("\n");
  }

  private writeFilters(lines: string[], folderPath: string): void {
    lines.push("filters:");
    lines.push("  and:");
    lines.push(`    - file.inFolder("${folderPath}")`);
    lines.push("");
  }

  private needsContentCoverFormula(views: ViewConfig[]): boolean {
    return views.some(
      (v) =>
        v.type === "gallery" &&
        v.cover &&
        (v.cover.type === "page_content" || v.cover.type === "page_content_first"),
    );
  }

  private writeFormulas(lines: string[], views: ViewConfig[]): void {
    if (!this.needsContentCoverFormula(views)) return;

    lines.push("formulas:");
    lines.push("  coverImage: file.embeds[0]");
    lines.push("");
  }

  private writePropertyDisplayNames(
    lines: string[],
    schema: Record<string, BasePropertySchema>,
  ): void {
    const entries = Object.entries(schema).filter(([, prop]) => prop.type !== "title");
    if (entries.length === 0) return;

    lines.push("properties:");
    for (const [name] of entries) {
      lines.push(`  ${this.yamlKey(name)}:`);
      lines.push(`    displayName: ${this.yamlValue(name)}`);
    }
    lines.push("");
  }

  private writeViews(
    lines: string[],
    views: ViewConfig[],
    schema: Record<string, BasePropertySchema>,
  ): void {
    const basesViews = views
      .map((v) => this.convertView(v, schema))
      .filter((v): v is NonNullable<typeof v> => v !== null);

    if (basesViews.length === 0) {
      lines.push("views:");
      lines.push("  - type: table");
      lines.push("    name: Table");
      return;
    }

    lines.push("views:");
    for (const view of basesViews) {
      lines.push(`  - type: ${view.type}`);
      lines.push(`    name: ${this.yamlValue(view.name)}`);

      if (view.order && view.order.length > 0) {
        lines.push("    order:");
        for (const col of view.order) {
          lines.push(`      - ${col}`);
        }
      }

      if (view.sort && view.sort.length > 0) {
        lines.push("    sort:");
        for (const s of view.sort) {
          lines.push(`      - column: ${s.column}`);
          lines.push(`        direction: ${s.direction}`);
        }
      }

      if (view.groupBy) {
        lines.push("    groupBy:");
        lines.push(`      property: ${view.groupBy.property}`);
        if (view.groupBy.direction) {
          lines.push(`      direction: ${view.groupBy.direction}`);
        }
      }

      if (view.image) {
        lines.push(`    image: ${view.image}`);
      }
    }
  }

  private convertView(
    view: ViewConfig,
    schema: Record<string, BasePropertySchema>,
  ): {
    type: BasesViewType;
    name: string;
    order?: string[];
    sort?: Array<{ column: string; direction: string }>;
    groupBy?: { property: string; direction?: string };
    image?: string;
  } | null {
    const basesType = NOTION_TO_BASES_VIEW[view.type];
    if (!basesType) return null;

    const result: {
      type: BasesViewType;
      name: string;
      order?: string[];
      sort?: Array<{ column: string; direction: string }>;
      groupBy?: { property: string; direction?: string };
      image?: string;
    } = {
      type: basesType,
      name: view.name || view.type,
    };

    if (view.properties && view.properties.length > 0) {
      const visible = view.properties
        .filter((p) => p.visible !== false)
        .map((p) => {
          const name = p.propertyName ?? this.resolvePropertyName(p.propertyId, schema);
          return name ? this.toNoteRef(name) : null;
        })
        .filter((name): name is string => !!name);

      if (visible.length > 0) {
        result.order = ["file.name", ...visible];
      }
    }

    if (view.sorts && view.sorts.length > 0) {
      result.sort = view.sorts
        .map((s) => {
          let column: string;
          if (s.property) {
            const propName = this.resolvePropertyName(s.property, schema) ?? s.property;
            column = this.toNoteRef(propName);
          } else if (s.timestamp) {
            column = s.timestamp === "created_time" ? "file.ctime" : "file.mtime";
          } else {
            return null;
          }
          return {
            column,
            direction: s.direction === "ascending" ? "ASC" : "DESC",
          };
        })
        .filter((s): s is NonNullable<typeof s> => s !== null);
    }

    if (view.groupBy) {
      const propName =
        view.groupBy.propertyName ?? this.resolvePropertyName(view.groupBy.propertyId, schema);
      if (propName) {
        result.groupBy = {
          property: this.toNoteRef(propName),
          direction:
            view.groupBy.sort === "ascending"
              ? "ASC"
              : view.groupBy.sort === "descending"
                ? "DESC"
                : undefined,
        };
      }
    }

    if (view.type === "gallery" && view.cover) {
      if (view.cover.type === "property" && view.cover.propertyId) {
        const propName = this.resolvePropertyName(view.cover.propertyId, schema);
        if (propName) result.image = this.toNoteRef(propName);
      } else if (view.cover.type === "page_cover") {
        result.image = "note.cover";
      } else if (view.cover.type === "page_content" || view.cover.type === "page_content_first") {
        result.image = "formula.coverImage";
      }
    }

    return result;
  }

  private toNoteRef(propertyName: string): string {
    return propertyName;
  }

  private resolvePropertyName(
    propertyId: string,
    schema: Record<string, BasePropertySchema>,
  ): string | undefined {
    for (const [name, prop] of Object.entries(schema)) {
      if (prop.id === propertyId) return name;
    }
    return undefined;
  }

  private yamlKey(key: string): string {
    if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(key)) return key;
    return `"${key.replace(/"/g, '\\"')}"`;
  }

  private yamlValue(value: string): string {
    if (/^[a-zA-Z0-9_-]+$/.test(value)) return value;
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
}
