import type { DatabaseViewsConfig, ViewConfig } from "../types/view.js";

export interface BasePropertySchema {
  readonly id: string;
  readonly type: string;
  readonly options?: Array<{ name: string; color?: string }>;
  readonly groups?: Array<{ name: string; color?: string; optionIds?: string[] }>;
}

export interface BaseFileOptions {
  readonly databaseId: string;
  readonly databaseName: string;
  readonly schema: Record<string, BasePropertySchema>;
  readonly viewsConfig: DatabaseViewsConfig;
  readonly folderPath: string;
}

type BasesViewType = "table" | "cards" | "list";

const NOTION_TO_BASES_VIEW: Record<string, BasesViewType | null> = {
  table: "table",
  gallery: "cards",
  list: "list",
  board: "cards",
  calendar: null,
  timeline: null,
  form: null,
  chart: null,
  map: null,
  dashboard: null,
};

export class BaseFileGenerator {
  generate(options: BaseFileOptions): string {
    const lines: string[] = [];

    lines.push(`# Auto-generated by Im-Nobsidian from Notion DB: ${options.databaseName}`);
    lines.push(`# Database ID: ${options.databaseId}`);
    lines.push("");

    this.writeFilters(lines, options.folderPath);
    this.writeFormulas(lines, options.viewsConfig.views);
    this.writePropertyDisplayNames(lines, options.schema);
    this.writeViews(lines, options.viewsConfig.views, options.schema);

    // YAML 파일은 말미 개행으로 끝낸다(POSIX 텍스트 관례·diff 안정성).
    return lines.join("\n") + "\n";
  }

  private writeFilters(lines: string[], folderPath: string): void {
    lines.push("filters:");
    lines.push("  and:");
    lines.push(`    - file.inFolder("${folderPath}")`);
    // `.base` 파일 자신도 폴더에 있어 카드로 잡히므로(빈 카드) markdown 노트만 남긴다.
    lines.push(`    - file.ext == "md"`);
    lines.push("");
  }

  private needsContentCoverFormula(views: ViewConfig[]): boolean {
    return views.some(
      (v) =>
        v.type === "gallery" &&
        v.cover &&
        (v.cover.type === "page_content" || v.cover.type === "page_content_first"),
    );
  }

  private writeFormulas(lines: string[], views: ViewConfig[]): void {
    if (!this.needsContentCoverFormula(views)) return;

    lines.push("formulas:");
    lines.push("  coverImage: file.embeds[0]");
    lines.push("");
  }

  private writePropertyDisplayNames(
    lines: string[],
    schema: Record<string, BasePropertySchema>,
  ): void {
    const entries = Object.entries(schema).filter(([, prop]) => prop.type !== "title");
    if (entries.length === 0) return;

    lines.push("properties:");
    for (const [name] of entries) {
      lines.push(`  ${this.yamlKey(name)}:`);
      lines.push(`    displayName: ${this.yamlValue(name)}`);
    }
    lines.push("");
  }

  private writeViews(
    lines: string[],
    views: ViewConfig[],
    schema: Record<string, BasePropertySchema>,
  ): void {
    const basesViews = views
      .map((v) => this.convertView(v, schema))
      .filter((v): v is NonNullable<typeof v> => v !== null);

    if (basesViews.length === 0) {
      lines.push("views:");
      lines.push("  - type: table");
      lines.push("    name: Table");
      return;
    }

    lines.push("views:");
    for (const view of basesViews) {
      lines.push(`  - type: ${view.type}`);
      lines.push(`    name: ${this.yamlValue(view.name)}`);

      if (view.order && view.order.length > 0) {
        lines.push("    order:");
        for (const col of view.order) {
          lines.push(`      - ${this.propRef(col)}`);
        }
      }

      if (view.sort && view.sort.length > 0) {
        lines.push("    sort:");
        for (const s of view.sort) {
          // Bases 정렬 항목의 키는 `property`다(`column` 아님 — Obsidian이 무시함).
          lines.push(`      - property: ${this.propRef(s.property)}`);
          lines.push(`        direction: ${s.direction}`);
        }
      }

      if (view.groupBy) {
        lines.push("    groupBy:");
        lines.push(`      property: ${this.propRef(view.groupBy.property)}`);
        if (view.groupBy.direction) {
          lines.push(`      direction: ${view.groupBy.direction}`);
        }
      }

      if (view.image) {
        lines.push(`    image: ${this.propRef(view.image)}`);
      }
    }
  }

  private convertView(
    view: ViewConfig,
    schema: Record<string, BasePropertySchema>,
  ): {
    type: BasesViewType;
    name: string;
    order?: string[];
    sort?: Array<{ property: string; direction: string }>;
    groupBy?: { property: string; direction?: string };
    image?: string;
  } | null {
    const basesType = NOTION_TO_BASES_VIEW[view.type];
    if (!basesType) return null;

    const result: {
      type: BasesViewType;
      name: string;
      order?: string[];
      sort?: Array<{ property: string; direction: string }>;
      groupBy?: { property: string; direction?: string };
      image?: string;
    } = {
      type: basesType,
      name: view.name || view.type,
    };

    if (view.properties && view.properties.length > 0) {
      const visible = view.properties
        .filter((p) => p.visible !== false)
        .map((p) => {
          const name = p.propertyName ?? this.resolvePropertyName(p.propertyId, schema);
          if (!name) return null;
          // title 타입 속성은 카드/표 제목(file.name)과 중복되고, 프론트매터엔
          // title 키가 없어(본문 H1·파일명으로 보존) 빈 컬럼으로 표시되므로 제외한다.
          if (schema[name]?.type === "title") return null;
          return this.toNoteRef(name);
        })
        .filter((name): name is string => !!name);

      if (visible.length > 0) {
        result.order = ["file.name", ...visible];
      }
    }

    if (view.sorts && view.sorts.length > 0) {
      result.sort = view.sorts
        .map((s) => {
          let property: string;
          if (s.property) {
            const propName = this.resolvePropertyName(s.property, schema) ?? s.property;
            property = this.toNoteRef(propName);
          } else if (s.timestamp) {
            property = s.timestamp === "created_time" ? "file.ctime" : "file.mtime";
          } else {
            return null;
          }
          return {
            property,
            direction: s.direction === "ascending" ? "ASC" : "DESC",
          };
        })
        .filter((s): s is NonNullable<typeof s> => s !== null);
    }

    if (view.groupBy) {
      const propName =
        view.groupBy.propertyName ?? this.resolvePropertyName(view.groupBy.propertyId, schema);
      if (propName) {
        result.groupBy = {
          property: this.toNoteRef(propName),
          direction:
            view.groupBy.sort === "ascending"
              ? "ASC"
              : view.groupBy.sort === "descending"
                ? "DESC"
                : undefined,
        };
      }
    }

    if (view.type === "gallery" && view.cover) {
      if (view.cover.type === "property" && view.cover.propertyId) {
        const propName = this.resolvePropertyName(view.cover.propertyId, schema);
        if (propName) result.image = this.toNoteRef(propName);
      } else if (view.cover.type === "page_cover") {
        result.image = "note.cover";
      } else if (view.cover.type === "page_content" || view.cover.type === "page_content_first") {
        result.image = "formula.coverImage";
      }
    }

    return result;
  }

  private toNoteRef(propertyName: string): string {
    return propertyName;
  }

  /**
   * 속성 참조(order/sort/groupBy/image)를 YAML로 안전하게 출력한다.
   * `file.name`·`formula.coverImage`·`note.cover` 같은 접두사 식별자와 공백 포함 일반 속성명은
   * 평문 스칼라로 안전하므로 그대로 두고, 콜론·해시·따옴표 등 YAML 메타문자가 있을 때만 인용한다.
   */
  private propRef(ref: string): string {
    if (/^[A-Za-z0-9_][A-Za-z0-9_. ]*$/.test(ref) && !ref.endsWith(" ")) return ref;
    return `"${ref.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }

  private resolvePropertyName(
    propertyId: string,
    schema: Record<string, BasePropertySchema>,
  ): string | undefined {
    // Notion `views.retrieve` 는 RAW 속성 id(예: `[jiM`)를 주지만
    // `databases.retrieve` 스키마는 URL-인코딩된 id(예: `%5BjiM`)를 준다.
    // 디코드 후 비교하지 않으면 "title" 외 모든 속성(cover/order/sort/groupBy)이
    // 매칭에 실패해 갤러리 커버·표시 컬럼이 통째로 사라진다.
    const target = this.decodeId(propertyId);
    for (const [name, prop] of Object.entries(schema)) {
      if (this.decodeId(prop.id) === target) return name;
    }
    return undefined;
  }

  private decodeId(id: string): string {
    try {
      return decodeURIComponent(id);
    } catch {
      return id;
    }
  }

  private yamlKey(key: string): string {
    if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(key)) return key;
    return `"${key.replace(/"/g, '\\"')}"`;
  }

  private yamlValue(value: string): string {
    if (/^[a-zA-Z0-9_-]+$/.test(value)) return value;
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
}
