import type { DatabaseViewsConfig, ViewConfig } from "../types/view.js";

export interface BasePropertySchema {
  readonly id: string;
  readonly type: string;
  readonly options?: Array<{ name: string; color?: string }>;
  readonly groups?: Array<{ name: string; color?: string; optionIds?: string[] }>;
}

export interface BaseFileOptions {
  readonly databaseId: string;
  readonly databaseName: string;
  readonly schema: Record<string, BasePropertySchema>;
  readonly viewsConfig: DatabaseViewsConfig;
  readonly folderPath: string;
}

type BasesViewType = "table" | "cards" | "list";

const NOTION_TO_BASES_VIEW: Record<string, BasesViewType | null> = {
  table: "table",
  gallery: "cards",
  list: "list",
  board: "cards",
  calendar: null,
  timeline: null,
  form: null,
  chart: null,
  map: null,
  dashboard: null,
};

const NOTION_TO_BASES_PROP_TYPE: Record<string, string> = {
  title: "text",
  rich_text: "text",
  number: "number",
  select: "text",
  multi_select: "text",
  status: "text",
  checkbox: "checkbox",
  date: "date",
  url: "text",
  email: "text",
  phone_number: "text",
  created_time: "date",
  last_edited_time: "date",
  people: "text",
  files: "text",
  formula: "text",
  rollup: "text",
  relation: "text",
  unique_id: "text",
  created_by: "text",
  last_edited_by: "text",
  verification: "text",
};

export class BaseFileGenerator {
  generate(options: BaseFileOptions): string {
    const lines: string[] = [];

    lines.push("---");
    lines.push(`# Auto-generated by Im-Nobsidian from Notion DB: ${options.databaseName}`);
    lines.push(`# Database ID: ${options.databaseId}`);
    lines.push("");

    this.writeProperties(lines, options.schema);
    this.writeSource(lines, options.folderPath);
    this.writeViews(lines, options.viewsConfig.views, options.schema);

    lines.push("---");
    return lines.join("\n");
  }

  private writeProperties(lines: string[], schema: Record<string, BasePropertySchema>): void {
    lines.push("properties:");

    for (const [name, prop] of Object.entries(schema)) {
      if (prop.type === "title") continue;

      const basesType = NOTION_TO_BASES_PROP_TYPE[prop.type] ?? "text";
      lines.push(`  ${this.yamlKey(name)}:`);
      lines.push(`    type: ${basesType}`);

      if (prop.options && prop.options.length > 0) {
        lines.push("    options:");
        for (const opt of prop.options) {
          lines.push(`      - ${this.yamlValue(opt.name)}`);
        }
      }
    }
    lines.push("");
  }

  private writeSource(lines: string[], folderPath: string): void {
    lines.push("source: folder");
    lines.push(`folder: ${folderPath}`);
    lines.push("");
  }

  private writeViews(
    lines: string[],
    views: ViewConfig[],
    schema: Record<string, BasePropertySchema>,
  ): void {
    const basesViews = views
      .map((v) => this.convertView(v, schema))
      .filter((v): v is NonNullable<typeof v> => v !== null);

    if (basesViews.length === 0) {
      lines.push("views:");
      lines.push("  - type: table");
      lines.push(`    name: Table`);
      return;
    }

    lines.push("views:");
    for (const view of basesViews) {
      lines.push(`  - type: ${view.type}`);
      lines.push(`    name: ${this.yamlValue(view.name)}`);

      if (view.visibleProperties && view.visibleProperties.length > 0) {
        lines.push("    properties:");
        for (const p of view.visibleProperties) {
          lines.push(`      - ${this.yamlValue(p)}`);
        }
      }

      if (view.sortBy) {
        lines.push(`    sortBy: ${this.yamlValue(view.sortBy)}`);
        lines.push(`    sortOrder: ${view.sortOrder ?? "ascending"}`);
      }

      if (view.groupBy) {
        lines.push(`    groupBy: ${this.yamlValue(view.groupBy)}`);
      }

      if (view.coverProperty) {
        lines.push(`    coverProperty: ${this.yamlValue(view.coverProperty)}`);
      }
    }
  }

  private convertView(
    view: ViewConfig,
    schema: Record<string, BasePropertySchema>,
  ): {
    type: BasesViewType;
    name: string;
    visibleProperties?: string[];
    sortBy?: string;
    sortOrder?: string;
    groupBy?: string;
    coverProperty?: string;
  } | null {
    const basesType = NOTION_TO_BASES_VIEW[view.type];
    if (!basesType) return null;

    const result: {
      type: BasesViewType;
      name: string;
      visibleProperties?: string[];
      sortBy?: string;
      sortOrder?: string;
      groupBy?: string;
      coverProperty?: string;
    } = {
      type: basesType,
      name: view.name || view.type,
    };

    if (view.properties && view.properties.length > 0) {
      const visible = view.properties
        .filter((p) => p.visible !== false)
        .map((p) => p.propertyName ?? this.resolvePropertyName(p.propertyId, schema))
        .filter((name): name is string => !!name);

      if (visible.length > 0) {
        result.visibleProperties = visible;
      }
    }

    if (view.sorts && view.sorts.length > 0) {
      const firstSort = view.sorts[0]!;
      if (firstSort.property) {
        const propName = this.resolvePropertyName(firstSort.property, schema) ?? firstSort.property;
        result.sortBy = propName;
        result.sortOrder = firstSort.direction;
      } else if (firstSort.timestamp) {
        result.sortBy = firstSort.timestamp;
        result.sortOrder = firstSort.direction;
      }
    }

    if (view.groupBy?.propertyName) {
      result.groupBy = view.groupBy.propertyName;
    } else if (view.groupBy?.propertyId) {
      const propName = this.resolvePropertyName(view.groupBy.propertyId, schema);
      if (propName) result.groupBy = propName;
    }

    if (view.type === "gallery" && view.cover?.type === "property" && view.cover.propertyId) {
      const propName = this.resolvePropertyName(view.cover.propertyId, schema);
      if (propName) result.coverProperty = propName;
    }

    return result;
  }

  private resolvePropertyName(
    propertyId: string,
    schema: Record<string, BasePropertySchema>,
  ): string | undefined {
    for (const [name, prop] of Object.entries(schema)) {
      if (prop.id === propertyId) return name;
    }
    return undefined;
  }

  private yamlKey(key: string): string {
    if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(key)) return key;
    return `"${key.replace(/"/g, '\\"')}"`;
  }

  private yamlValue(value: string): string {
    if (/^[a-zA-Z0-9_-]+$/.test(value)) return value;
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
}
